akun/urls.py
from django.urls import path
from . import views

app_name ='akun'

urlpatterns = [
    path('', views.profile, name ='profile'),
    path('hasilprofile/', views.profile_dua , name = 'profile_dua'),
    path('editprofile/<int:pk>/', views.update_profile , name = 'update_profile'),
    path('cobalist/', views.cobaList, name = 'list'),
    path('cobacreate/', views.cobaCreate, name = 'create'),

]

assessment/urls.py
from django.urls import path

from . import views

app_name = 'assessment'

urlpatterns = [
    path('', views.landing, name='landing'),
    path('result/<str:id>/', views.result, name='result'),
    path('result/all', views.results, name='results'),
    path('hide/<str:id>/', views.hide, name='hide'),
    path('test/', views.index, name='index')

]

coronahworry/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('workout/', include(('workout.urls', 'workout'), namespace = 'workout')),
    path('profile/', include(('akun.urls', 'akun'), namespace = 'akun')),
    path('assessment/', include(('assessment.urls', 'assessment'), namespace='assessment')),
    path('curhat/', include(('komentar.urls', 'komentar'), namespace = 'komentar')),
    path('curhat/', include(('postingan.urls', 'postingan'), namespace = 'postingan')),
    path('', include(('main.urls', 'main'), namespace='main')),
]



assessment/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Assessment(models.Model):
    yes = True
    no = False
    BOOLEAN_CHOICES = [(yes, 'Ya'), (no, 'Tidak/Tidak Tahu')]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    suhu = models.BooleanField(choices=BOOLEAN_CHOICES)
    sesak = models.BooleanField(choices=BOOLEAN_CHOICES)
    batuk = models.BooleanField(choices=BOOLEAN_CHOICES)
    kontak_positif = models.BooleanField(choices=BOOLEAN_CHOICES)
    kontak_gejala = models.BooleanField(choices=BOOLEAN_CHOICES)
    status = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)

assessment/forms.py
from django import forms
from assessment.models import Assessment


class AssessmentForm(forms.ModelForm):
    class Meta:
        model = Assessment
        fields = {
            'suhu',
            'batuk',
            'kontak_positif',
            'kontak_gejala',
            'sesak'
        }

assessment/views.py
from django.shortcuts import render, redirect
from assessment.models import Assessment
from assessment.forms import AssessmentForm
from django.http import JsonResponse

# Create your views here.


def index(request):
    if request.user.is_authenticated:
        form = AssessmentForm(request.POST or None)

        if request.POST.get('action') == 'post':
            data = request.POST
            form = Assessment(user=request.user, suhu=bool(data['suhu']), batuk=bool(data['batuk']), sesak=bool(data['sesak']),
                              kontak_positif=bool(data['kontak_positif']), kontak_gejala=bool(data['kontak_gejala']))
            form.save()
            response = {}
            response['suhu'] = bool(data['suhu'])
            response['batuk'] = bool(data['batuk'])
            response['sesak'] = bool(data['sesak'])
            response['kontak_positif'] = bool(data['kontak_positif'])
            response['kontak_gejala'] = bool(data['kontak_gejala'])
            response['id'] = form.id

            return JsonResponse(response)

        context = {
            'form': form
        }
        return render(request, 'assessment/assessment.html', context)
    else:
        return redirect('main:login')


def landing(request):
    return render(request, 'assessment/landing.html')


def result(request, id):
    data = Assessment.objects.filter(user=request.user, id=id, status=1)
    if(len(data) != 0):
        counterGejala = 0
        if(data[0].suhu == True):
            counterGejala += 1
        if(data[0].sesak == True):
            counterGejala += 1
        if(data[0].batuk == True):
            counterGejala += 1

        if(counterGejala == 0):
            if(data[0].kontak_gejala == True and data[0].kontak_positif == True):
                return render(request, 'assessment/medium.html')
            elif(data[0].kontak_gejala == True and data[0].kontak_positif == False):
                return render(request, 'assessment/low.html')
            elif(data[0].kontak_gejala == False and data[0].kontak_positif == True):
                return render(request, 'assessment/low.html')
            else:
                return render(request, 'assessment/low.html')

        elif(counterGejala == 1):
            if(data[0].kontak_gejala == True and data[0].kontak_positif == True):
                return render(request, 'assessment/medium.html')
            elif(data[0].kontak_gejala == True and data[0].kontak_positif == False):
                return render(request, 'assessment/medium.html')
            elif(data[0].kontak_gejala == False and data[0].kontak_positif == True):
                return render(request, 'assessment/medium.html')
            else:
                return render(request, 'assessment/low.html')

        else:
            if(data[0].kontak_gejala == True and data[0].kontak_positif == True):
                return render(request, 'assessment/high.html')
            elif(data[0].kontak_gejala == True and data[0].kontak_positif == False):
                return render(request, 'assessment/medium.html')
            elif(data[0].kontak_gejala == False and data[0].kontak_positif == True):
                return render(request, 'assessment/high.html')
            else:
                return render(request, 'assessment/medium.html')
    else:
        return render('assessment:index')


def results(request):
    if request.user.is_authenticated:
        datas = Assessment.objects.all().filter(user=request.user, status=1)
        context = {
            'datas': datas
        }
        return render(request, 'assessment/results.html', context)
    else:
        return redirect('main:login')


def hide(request, id):
    selected_data = Assessment.objects.get(
        user=request.user, id=id)
    selected_data.status = 0
    selected_data.save()
    return redirect('assessment:results')

templates/assessment/assessment.html
{% extends '../base/base.html' %} {% load static %} {%block title%} Assessment |
coroNAHworry {%endblock%} {% block customcss %}
<link rel="stylesheet" href="{% static 'css/assesment/assessment.css' %}" />
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
/>
{% endblock %} {%block content%}
<div id="test">
  <div class="assessTitleDiv">
    <h1 class="assessTitle">
      Corona Assesment
      <img
        src="https://vik.kompas.com/viruscorona/images/virus.png"
        alt="virus"
      />
    </h1>
    {{data}}
  </div>
  <form id="createForm" method="POST">
    {% csrf_token %}
    <div>
      <div class="questionDiv">
        <label
          >Apakah anda mengalami demam dengan suhu di atas 38°C
          (100.4°F)?</label
        >
        {{form.suhu}}
      </div>
      <div class="questionDiv">
        <label>Apakah ada batuk (atau disertai dengan batuk)?</label>
        {{form.batuk}}
      </div>
      <div class="questionDiv">
        <label
          >Apakah anda mengalami sesak saat bernafas (tekanan pada dada)?</label
        >
        {{form.sesak}}
      </div>
      <div class="questionDiv">
        <label
          >Apakah terdapat riwayat kontak (misalnya: berjabat tangan, mengobrol
          lama, berada dalam satu ruangan) dengan orang yang sudah dinyatakan
          positif terinfeksi virus Corona dalam 14 hari terakhir?</label
        >
        {{form.kontak_positif}}
      </div>
      <div class="questionDiv">
        <label
          >Apakah ada kontak (misalnya: berjabat tangan, mengobrol lama, berada
          dalam satu ruangan) dengan orang yang memiliki gejala flu, yaitu
          demam, batuk, dan pilek, atau dengan orang yang diduga terinfeksi
          virus Corona dalam 14 hari terakhir?</label
        >
        {{form.kontak_gejala}}
      </div>
      <div>
        <a
          href="{% url 'assessment:landing' %}"
          class="btn btn-outline-danger"
          style="margin-top: 20px; margin-right: 10px"
          >Back</a
        >
        <input
          style="margin-top: 20px"
          class="btn btn-primary"
          type="submit"
          value="Submit"
          onclick="create()"
        />
      </div>
    </div>
  </form>
</div>
<div id="id01" class="modal">
  <form class="modal-content" action="">
    <div class="container-modal">
      <h1>Thank you for using coroNAHworry!</h1>
      <img
        src="https://image.freepik.com/free-vector/positive-people-facing-new-normal_23-2148636539.jpg"
      />
      <p>
        Your result is here. Don't forget to always wear mask and do social
        distancing. Hope you and your family are healthy and safe during these
        uncertain and unprecedented times.
      </p>
      <div class="clearfix">
        <a id="cancelbtn" class="btn btn-outline-danger">Back for another</a>
        <a id="hidebtn" class="btn btn-outline-primary">Check</a>
      </div>
    </div>
  </form>
</div>
{% endblock %} {%block customjs%}
<script>
  function create() {
    event.preventDefault();
    var suhu = document.getElementById("id_suhu").value;
    var batuk = document.getElementById("id_batuk").value;
    var sesak = document.getElementById("id_sesak").value;
    var kontak_positif = document.getElementById("id_kontak_positif").value;
    var kontak_gejala = document.getElementById("id_kontak_gejala").value;

    $.ajax({
      type: "POST",
      url: "{% url 'assessment:index' %}",
      dataType: "json",
      data: {
        suhu: suhu,
        batuk: batuk,
        sesak: sesak,
        kontak_positif: kontak_positif,
        kontak_gejala: kontak_gejala,
        action: "post",
        csrfmiddlewaretoken: $("input[name=csrfmiddlewaretoken]").val(),
      },
      success: function (data) {
        document.getElementById("id01").style.display = "block";
        var modal = document.getElementById("id01");

        var href = String("{% url 'assessment:result' 999 %}").replace(
          /999/gi,
          data.id
        );

        a = document.getElementById("hidebtn");
        a.setAttribute("href", href);

        window.onclick = function (event) {
          if (event.target == modal) {
            modal.style.display = "none";
          }
          if (event.target == cancelbtn) {
            modal.style.display = "none";
            $("#createForm")[0].reset();
          }
        };
      },
      error: function () {
        console.log("Error");
      },
    });
  }
</script>

{% endblock %}

templates/assessment/high.html
{% extends '../base/base.html' %} {% load static %} {%block title%} Assessment |
coroNAHworry {%endblock%} {%block customcss %}
<link rel="stylesheet" href="{% static 'css/assesment/high.css' %}" />
{%endblock%} {%block content%}
<div class="high">
  <div class="golonganDiv">
    <h1>Kemungkinan anda terpapar virus Covid-19 tergolong</h1>
    <h1 id="type">TINGGI</h1>
  </div>
  <div class="content">
    <div class="img">
      <img
        src="https://images.vexels.com/media/users/3/193280/isolated/preview/8239ac53cb85b93a6786e3c5e665acfa-covid-19-symptom-girl-headache-by-vexels.png"
        alt="high-img"
      />
    </div>
    <div class="contentText">
      <p>Ini hal yang dapat dilakukan dan rekomendasi agar anda tetap aman</p>
      <ul>
        <li>
          Segera lakukan PCR/swab test di rumah sakit/fasilitas kesehatan
          terdekat
        </li>
        <li>
          Anda diharapkan untuk segera mengisolasi diri anda selama 14 hari
          dirumah, dan hindari kontak fisik dengan orang lain
        </li>
        <li>
          Anda diharapkan tidak keluar rumah untuk melindungi orang-orang
          disekitar anda
        </li>
        <li>
          Patuhi 3M : Memakai masker, Mencuci tangan minimal 20 detik, Menjaga
          jarak dengan orang lain
        </li>
        <li>
          Jika gejala yang anda alami hanya memburuk, segera hubungi rumah
          sakit/fasilitas kesehatan terdekat
        </li>
      </ul>
    </div>
  </div>
  <div>
    <form method="POST" action="{% url 'assessment:results' %}">
      {% csrf_token %}
      <button class="btn btn-primary">Go to all results</button>
    </form>
  </div>
</div>
{%endblock%}

templates/assessment/landing.html
{% extends '../base/base.html' %} {% load static %} {%block title%} Assessment |
coroNAHworry {%endblock%} {% block customcss %}
<link rel="stylesheet" href="{% static 'css/assesment/landing.css' %}" />
{% endblock %} {%block content%}
<div class="landing-div">
  <div class="landing-img">
    <img
      src="https://portal.posipedia.co/wp-content/uploads/2020/06/covid19-protocolos-bioseguridad.png"
    />
  </div>
  <div class="content">
    <h1>COVID-19 self-assessment</h1>
    <p>
      This resource can help you decide what kind of medical care you might need
      for COVID‑19
    </p>
    <div class="buttons">
      <a href="{% url 'assessment:index' %}" class="btn btn-outline-primary">
        Take the test
      </a>
      <a href="{% url 'assessment:results' %}" class="btn btn-outline-primary">
        See my results
      </a>
    </div>
  </div>
</div>
{% endblock %}

templates/assessment/low.html
{% extends '../base/base.html' %} {% load static %} {%block title%} Assessment |
coroNAHworry {%endblock%} {%block customcss %}
<link rel="stylesheet" href="{% static 'css/assesment/low.css' %}" />
{%endblock%} {%block content%}
<div class="low">
  <div class="golonganDiv">
    <h1>Kemungkinan anda terpapar virus Covid-19 tergolong</h1>
    <h1 id="type">RENDAH</h1>
  </div>
  <div class="content">
    <div class="img">
      <img
        src="https://images.vexels.com/media/users/3/193239/isolated/preview/e83db85552ee35f6276411c9f19d982d-covid-19-boy-character-icon-by-vexels.png"
        alt="low-img"
      />
    </div>
    <div class="contentText">
      <p>Ini hal yang dapat dilakukan dan rekomendasi agar anda tetap aman</p>
      <ul>
        <li>Coba untuk tetap di rumah dan mengurangi kegiatan di luar</li>
        <li>Patuhi protokol kesehatan</li>
        <li>
          Patuhi 3M : Memakai masker, Mencuci tangan minimal 20 detik, Menjaga
          jarak dengan orang lain
        </li>
        <li>
          Jika anda diharuskan ke luar, prioritaskan ruangan dengan sirkulasi
          udara yang baik
        </li>
      </ul>
    </div>
  </div>
  <div>
    <form method="POST" action="{% url 'assessment:index' %}">
      {% csrf_token %}
      <button class="btn btn-primary">Go to all results</button>
    </form>
  </div>
</div>
{%endblock%}

templates/assessment/medium.html
{% extends '../base/base.html' %} {% load static %} {%block title%} Assessment |
coroNAHworry {%endblock%} {%block customcss %}
<link rel="stylesheet" href="{% static 'css/assesment/medium.css' %}" />
{%endblock%} {%block content%}
<div class="high">
  <div class="golonganDiv">
    <h1>Kemungkinan anda terpapar virus Covid-19 tergolong</h1>
    <h1 id="type">SEDANG</h1>
  </div>
  <div class="content">
    <div class="img">
      <img
        src="https://images.vexels.com/media/users/3/193236/isolated/preview/1590950fb0eb48ffee67d8d3d86b35ea-covid-19---cone-de-personagem-de-menina-loira-by-vexels.png"
        alt="high-img"
      />
    </div>
    <div class="contentText">
      <p>Ini hal yang dapat dilakukan dan rekomendasi agar anda tetap aman</p>
      <ul>
        <li>
          Anda diharapkan untuk segera mengisolasi diri anda selama 14 hari
          dirumah, dan hindari kontak fisik dengan orang lain
        </li>
        <li>Prioritas aktivitas pada ruangan yang bersirkulasi baik</li>
        <li>
          Jika anda diwajibkan keluar rumah, tolong perhatikan protokol
          kesehatan yang berlaku
        </li>
        <li>
          Patuhi 3M : Memakai masker, Mencuci tangan minimal 20 detik, Menjaga
          jarak dengan orang lain
        </li>
        <li>
          Jika gejala yang anda alami hanya memburuk, segera hubungi rumah
          sakit/fasilitas kesehatan terdekat
        </li>
      </ul>
    </div>
  </div>
  <div>
    <form method="POST" action="{% url 'assessment:index' %}">
      {% csrf_token %}
      <button class="btn btn-primary">Re-take Assesment</button>
    </form>
  </div>
</div>
{%endblock%}

templates/assessment/results.html
{% extends '../base/base.html' %} {% load static %} {%block title%} Assessment |
coroNAHworry {%endblock%} {% block customcss %}
<link rel="stylesheet" href="{% static 'css/assesment/results.css' %}" />
{% endblock %} {%block content%}
<div class="results-div">
  <div class="header-div">
    <h1>Your assessment results</h1>
    <a href="{% url 'assessment:index' %}" class="btn btn-outline-primary"
      >Take a test</a
    >
  </div>
  <table id="table" class="table">
    <thead>
      <tr>
        <th scope="col">No.</th>
        <th scope="col">Assessment</th>
        <th scope="col">Date</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      {% if datas %} {% for data in datas %}
      <tr name="row">
        <td onclick="coba({{data.id}})"></td>
        <td onclick="coba({{data.id}})">Assessment #</td>
        <td onclick="coba({{data.id}})">{{data.created_at}}</td>
        <td>
          <a class="btn btn-outline-danger" onclick="confirmation({{data.id}})"
            >Hide</a
          >
        </td>
      </tr>
      {% endfor %} {% endif %}
    </tbody>
  </table>
</div>
<div id="id01" class="modal">
  <form class="modal-content" action="">
    <div class="container-modal">
      <h1>Hide this Assessment</h1>
      <img
        src="https://www.freeiconspng.com/uploads/16x16-x-icon-vector-16.png"
        alt="x"
      />
      <p>Are you sure you want to hide this assessment?</p>
      <div class="clearfix">
        <a id="cancelbtn" class="btn btn-outline-primary">Cancel</a>
        <a id="hidebtn" class="btn btn-outline-danger">Hide</a>
      </div>
    </div>
  </form>
</div>
{% endblock %} {% block customjs %}
<script>
  $(document).ready(function () {
    var table = $("table")[0];
    if (table.rows.length < 2) {
      document.getElementById("table").style.display = "none";
      $(".results-div").append(
        "<div id='imgdiv'><img class='empty-img' alt='notfound' src='https://ouch-cdn.icons8.com/preview/606/90c1f2d7-b42f-4d7e-9d17-e183179862b7.png'/></div>"
      );
      $("#imgdiv").prepend(
        "<h1>Couldn't find any assessment results of yours!</h1>"
      );
    }

    $("[name='row']").hover(
      function () {
        $(this).addClass("highlight");
      },
      function () {
        $(this).removeClass("highlight");
      }
    );
  });

  function coba(id) {
    location.href = String("{% url 'assessment:result' 999 %}").replace(
      /999/gi,
      id
    );
  }

  function confirmation(id) {
    document.getElementById("id01").style.display = "block";
    var modal = document.getElementById("id01");

    var href = String("{% url 'assessment:hide' 999 %}").replace(/999/gi, id);

    a = document.getElementById("hidebtn");
    a.setAttribute("href", href);

    window.onclick = function (event) {
      if (event.target == modal || event.target == cancelbtn) {
        modal.style.display = "none";
      }
    };
  }
</script>
{% endblock %}