akun/urls.py
from django.urls import path
from . import views

app_name ='akun'

urlpatterns = [
    path('', views.profile, name ='profile'),
    path('hasilprofile/', views.profile_dua , name = 'profile_dua'),
    path('editprofile/<int:pk>/', views.update_profile , name = 'update_profile'),
    path('cobalist/', views.cobaList, name = 'list'),
    path('cobacreate/', views.cobaCreate, name = 'create'),

]

assessment/urls.py
from django.urls import path

from . import views

app_name = 'assessment'

urlpatterns = [
    path('', views.landing, name='landing'),
    path('result/<str:id>/', views.result, name='result'),
    path('result/all', views.results, name='results'),
    path('hide/<str:id>/', views.hide, name='hide'),
    path('test/', views.index, name='index')

]

coronahworry/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('workout/', include(('workout.urls', 'workout'), namespace = 'workout')),
    path('profile/', include(('akun.urls', 'akun'), namespace = 'akun')),
    path('assessment/', include(('assessment.urls', 'assessment'), namespace='assessment')),
    path('curhat/', include(('komentar.urls', 'komentar'), namespace = 'komentar')),
    path('curhat/', include(('postingan.urls', 'postingan'), namespace = 'postingan')),
    path('', include(('main.urls', 'main'), namespace='main')),
]



main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.akun_login, name='login'),
    path('logout/', views.akun_logout, name='logout'),
    path('register/', views.akun_register, name='register'),
]

workout/urls.py
from django.urls import path

from . import views

app_name = 'workout'

urlpatterns = [
    path('cobalist/', views.cobaList, name = 'list'),
    path('cobacreate/', views.cobaCreate, name = 'create'),
    path('list/', views.list_work, name='listwork'),
    path('create/', views.create_work, name='creatework'),
    path('', views.hitung_bmi, name='hitungbmi'),
]

templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <title>{% block title %}{% endblock %} | coroNAHworry 2</title>

	<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
	{% block customcss %}{% endblock %}
</head>

<body class="bg-light">
	{% include './navbar.html' %}
<main role="main" class="container" >

	{% block content %}
	
	{% endblock %}
</main>

<div class="fixed-top" style="margin-top: 4.5rem; margin-right: 3rem; z-index: -1;">
	<div aria-live="polite" aria-atomic="true" style="position: relative; min-height: 200px;" id="toast-div"></div>
</div>

</body>




	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
	<script>
	  function getActiveNavbar() {
      let nowURL = window.location.pathname;
      let menuActive = "#" + nowURL.slice(nowURL.indexOf('/') + 1, nowURL.indexOf('/',1)) + "-navbar";
      $(menuActive).addClass('active');
    }
	$(document).ready(getActiveNavbar);
	</script>
	{% block customjs %}{% endblock %}
</body>
</html>

templates/base/footer.html
<!-- Footer -->
<div class="footer">
  <footer class="page-footer font-small" style="background-color:#065a6ec7;">
    <!-- Footer Text -->
    <div class="container-fluid text-center text-md-left">
      <div class="container mx-5 pt-5 px-5">
          <!-- Content -->
          <div class="text-center text-white">
            <h5 class="text-uppercase font-weight-bold">About Website</h5>
          <p>coroNAHworry merupakan website yang memiliki tujuan untuk menghilangkan kebosanan ditengah pandemi, dengan
          berbagai fitur seperti assessment corona, berbagi curhatan, dan berbagi kegiatan.</p>
  
          <h5 class="text-uppercase font-weight-bold">Group Member</h5>
          <p>Kak Daus | Josias | Vanni | Faishol | Adit</p>
          <p><b>Made by Group C03</b></p>
          </div>
        </div>
      </div>
    </div>
  </footer>
</div>

<!-- Footer -->

templates/base/navbar.html
<style>
  .navbar .navbar-nav .nav-item .nav-link:link,
  .navbar .navbar-nav .nav-item .nav-link:visited {
    color: white;
    margin-right: 10px;
    margin-top: 10px;
  }

  .navbar .navbar-nav .nav-item .nav-link:hover,
  .navbar .navbar-nav .nav-item .nav-link:active {
    color: black;
    background-color: white;
  }
</style>

<nav
  class="navbar navbar-expand-md fixed-top navbar-dark"
  style="background-color: #065a6ec7"
>
  <div class="container">
    <a class="navbar-brand" href="/">
      <strong>coroNAHworry 2</strong>
    </a>
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarCollapse"
      aria-controls="navbarCollapse"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div id="navbarCollapse" class="collapse navbar-collapse">
      <ul class="navbar-nav ml-auto">
        {% if user.username %}
        <li id="assessment-navbar" class="nav-item">
          <a class="nav-link" href="{% url 'assessment:landing' %}"
            >Assessment</a
          >
        </li>
        <li id="workout-navbar" class="nav-item">
          <a class="nav-link" href="{% url 'workout:listwork' %}"
            >Activity & Workout</a
          >
        </li>
        <li id="bmi-navbar" class="nav-item">
          <a class="nav-link" href="{% url 'workout:hitungbmi' %}">BMI</a>
        </li>
        <li id="curhat-navbar" class="nav-item">
          <a class="nav-link" href="{% url 'postingan:index' %}">Curhat</a>
        </li>
        <li id="profile-navbar" class="nav-item">
          <a class="nav-link" href="{% url 'akun:profile' %}">Profile</a>
        </li>
        <li id="logout-navbar" class="nav-item">
          <a class="nav-link" href="{% url 'main:logout' %}">Log out</a>
        </li>
        {% else %}
        <li id="login-navbar" class="nav-item">
          <a class="nav-link" href="{% url 'main:login' %}">Log in</a>
        </li>
        <li id="register-navbar" class="nav-item">
          <a class="nav-link" href="{% url 'main:register' %}">Register</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>