akun/urls.py
from django.urls import path
from . import views

app_name ='akun'

urlpatterns = [
    path('', views.profile, name ='profile'),
    path('hasilprofile/', views.profile_dua , name = 'profile_dua'),
    path('editprofile/<int:pk>/', views.update_profile , name = 'update_profile'),
    path('cobalist/', views.cobaList, name = 'list'),
    path('cobacreate/', views.cobaCreate, name = 'create'),

]

coronahworry/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('workout/', include(('workout.urls', 'workout'), namespace = 'workout')),
    path('profile/', include(('akun.urls', 'akun'), namespace = 'akun')),
    path('assessment/', include(('assessment.urls', 'assessment'), namespace='assessment')),
    path('curhat/', include(('komentar.urls', 'komentar'), namespace = 'komentar')),
    path('curhat/', include(('postingan.urls', 'postingan'), namespace = 'postingan')),
    path('', include(('main.urls', 'main'), namespace='main')),
]



akun/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    nama = models.CharField(max_length=50,  null=True, blank=True)
    umur  = models.IntegerField(null=True, blank=True)
    domisili = models.CharField(max_length=50, null=True, blank=True)
    berat_badan = models.IntegerField(null=True, blank=True, default=0)
    tinggi_badan = models.IntegerField(null=True, blank=True, default=0)
    user = models.OneToOneField(User, on_delete = models.CASCADE)

    def hitung_bmi(self):
        if (self.berat_badan == 0 or self.tinggi_badan == 0):
            return 0;
        else:
            res = (self.berat_badan / ((self.tinggi_badan/100)**2))
            return round(res,2)

akun/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile

class UserForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['nama', 'umur', 'domisili', 'berat_badan', 'tinggi_badan']

    def edit_obj(self,profile_obj):
        profile_obj.nama = self.cleaned_data['nama']
        profile_obj.umur = self.cleaned_data['umur']
        profile_obj.domisili = self.cleaned_data['domisili']
        profile_obj.berat_badan = self.cleaned_data['berat_badan']
        profile_obj.tinggi_badan = self.cleaned_data['tinggi_badan']
        profile_obj.save()

akun/views.py
from django.shortcuts import render, redirect
from .models import Profile
from .forms import UserForm
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt


# Create your views here.
def profile(request): 
    return redirect('akun:profile_dua')
    

def profile_dua(request): # ambil data user
    if request.user.is_authenticated:
        get_data_dua = None
        try:
            get_data_dua = Profile.objects.get(user = request.user)
        except:
            get_data_dua = Profile.objects.create(user = request.user)

        context = {'data':get_data_dua}
        return render(request, 'akun/hasilProfile.html', context)
    else:
        return redirect('main:login')

def update_profile(request, pk): #update data user
    if request.user.is_authenticated:
        get_data_dua = Profile.objects.get(id=pk)
        get_profile = UserForm(instance = get_data_dua)
        
        if request.method == "POST":
            get_profile = UserForm(request.POST, instance=get_data_dua)
            if get_profile.is_valid():
                get_profile.edit_obj(get_data_dua)
                return redirect('akun:profile_dua')
        context = {'edit':get_profile, 'user':get_data_dua}
        return render(request, 'akun/editProfile.html', context)
    else:
        return redirect('main:login')

# fungsi Json
@csrf_exempt
def cobaCreate(request):
    responJson = {'error':'not allowed'}
    
    status_code = 405

    if request.method == 'POST':
        nama = request.POST.get('nama')
        print(nama)
        umur = request.POST.get('umur')
        domisili = request.POST.get('domisili')
        berat = request.POST.get('berat_badan')
        tinggi = request.POST.get('tinggi_badan')
        
        # desc = request.POST.get('desc')
        # duration = request.POST.get('duration')
        pk = request.POST.get('id')
        get_data_dua = Profile.objects.get(id=pk)
        get_data_dua.nama = nama
        get_data_dua.umur = umur
        get_data_dua.domisili = domisili
        get_data_dua.berat_badan = berat
        get_data_dua.tinggi_badan = tinggi

        get_data_dua.save()

        responJson = {'status': 'ok'}
        status_code = 200

    return JsonResponse(responJson, status=status_code)

def cobaList(request):
    if not request.user.is_authenticated:
        responJson = {'error': 'forbidden'}
        status_code = 403

    else :
        profile = Profile.objects.filter(user=request.user)
        responContent = []
        for i in profile :
            temp = {'nama':i.nama, 'umur':i.umur,'domisili':i.domisili, 'berat':i.berat_badan, 'tinggi':i.tinggi_badan}
            responContent.append(temp)
        responJson = {'content':responContent}
        status_code = 200
    return JsonResponse(responJson, status=status_code)

templates/akun/editProfile.html
{% extends "base/base.html" %}

{% load static %}


{% block title %}Edit Profile{% endblock %}
{% block customcss %}
<link rel="stylesheet" href="{% static "css/profile.css" %}">
{% endblock %}
{% block content %}

<br>
<center>
    <legend class="border-bottom mb-4">Profile Info <img src = "{% static 'img/profile/download.png' %}"width=20 height=20> </legend>
</center>

    <div class="card mb-3"> 
        <div class="card-body">

            <input type ="text" name="id" value = "{{user.pk}}" hidden id="userid">

            <div>
               
                <div class="row">
        
                    <div class="col-sm-3">
                        <h6 class="mb-0">Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary" >
                        <input name='nama' id='nama' class="form-control" cols="40" rows="5" required maxlength="200" placeholder="Tulis nama">
                    </div>
                </div>
            <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Age </h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        <input name='age' id='umur' class="form-control" cols="40" rows="5" required maxlength="200" placeholder="Tulis umur">
                    </div>
                </div>
            <hr>
                <div class="row">
                    <div class="col-sm-3">
                    <h6 class="mb-0">Residence</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        <input name='residence' id='domisili' class="form-control" cols="40" rows="5" required maxlength="200" placeholder="Tulis domisili">
                    </div>
                </div>
            <hr>
                <div class="row">
                    <div class="col-sm-3">
                    <h6 class="mb-0">Weight</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        <input name='weight' id='berat' class="form-control" cols="40" rows="5" required maxlength="200" placeholder="Tulis berat"> Kg
                    </div>
                </div>
            <hr>
                <div class="row">
                    <div class="col-sm-3">
                    <h6 class="mb-0">Height </h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        <input name='height' id='tinggi' class="form-control" cols="40" rows="5" required maxlength="200" placeholder="Tulis tinggi"> Cm
                    </div>
                </div>
                <br>
                <div class="form-group">
                    <center>
                    <button  class="btn btn-success" id="submit">Save</button>
                    <a href="{% url 'akun:profile_dua' %}" class="btn btn-danger">Back</a>
                    </center>
                </div>
            </div>
        </div>
    </div>



{% endblock %}

{% block customjs %}
<script src="{% static 'js/profile.js' %}"></script>


{% endblock %}

templates/akun/hasilProfile.html
{% extends "base/base.html" %}

{% load static %}

{% block title %}Profile{% endblock %}
{% block customcss %}
<link rel="stylesheet" href="{% static "css/profile.css" %}">
{% endblock %}
{% block content %}

<br>

<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>PENTING!</strong> Silahkan memasukkan data diri anda melalui Edit button
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

<!-- <div class="row gutters-sm">
    <div class="col-md-4 mb-3">
        <div class="card">
            <div class="card-body">
                <div class="d-flex flex-column align-items-center text-center">
                    <img src="{% static 'img/profile/default.png' %}" alt="Admin" class="rounded-circle" width="150">
                    <div class="mt-3">
                        <h4>{{ data.nama }}</h4>
                        <p class="text-secondary mb-1">{{ user.username }}</p>
                        <p class="text-muted font-size-sm"> coroNAHworry visitors</p>
                        <a href="{% url 'akun:update_profile' data.id %}" class="btn btn-secondary">Edit</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <h1>Profile Info</h1>
        <div class="card mb-3">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{ data.nama }}
                    </div>
                </div>
            <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Age </h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{ data.umur }}
                    </div>
                </div>
            <hr>
                <div class="row">
                    <div class="col-sm-3">
                    <h6 class="mb-0">Residence</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{ data.domisili }}
                    </div>
                </div>
            <hr>
                <div class="row">
                    <div class="col-sm-3">
                    <h6 class="mb-0">Weight</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{ data.berat_badan }} Kg
                    </div>
                </div>
            <hr>
                <div class="row">
                    <div class="col-sm-3">
                    <h6 class="mb-0">Height </h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{ data.tinggi_badan }} Cm
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> -->

<div class="row gutters-sm">
    <div class="col-md-4 mb-3">
        <div class="card">
            <div class="card-body">
                <div class="d-flex flex-column align-items-center text-center">
                    <div class="circle">
                        <img class="profile-pic" src="http://cdn.cutestpaw.com/wp-content/uploads/2012/07/l-Wittle-puppy-yawning.jpg">
                  
                    </div>
                    <div class="p-image upload-button">
                        <i class="fa fa-camera"></i> Change
                    </div>
                    <input class="file-upload" type="file" accept="image/*"/>
                       
                    <br>
                    <br> 
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    
                     
                    <!-- <img src="{% static 'img/profile/default.png' %}" alt="Admin" class="rounded-circle" width="150"> -->
                    <div class="mt-3">
                        <h4 >{{ data.nama }}</h4>
                        <p class="text-secondary mb-1">{{ user.username }}</p>
                        <p class="text-muted font-size-sm"> coroNAHworry visitors</p>
                        <a href="{% url 'akun:update_profile' data.id %}" class="btn btn-secondary">Make You Profile</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-8" id = "ini-hasil">
    <!-- Hasil profile info disini -->
    </div>
</div> 


{% endblock %}

{% block customjs %}
<script src="{% static 'js/hasil.js' %}"></script>
<script src="{% static 'js/profile.js' %}"></script>

{% endblock %}

templates/akun/profile.html
{% extends '../base/base.html' %}

{% load static %}

{% block title %}Profile{% endblock %}

{% block content %}
    <br>
    <div class = "title">
      <h1> Profile </h1>
    </div>
    
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <strong>PENTING!</strong> Silahkan memasukkan data diri melalui edit button
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>

    <div class="card text-center">
      <div class="card-body">
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Profile Info</legend>
              <p> Silahkan memasukkan data diri anda terlebih dahulu</p>
              <p>Nama : {{ profile.nama }}</p>
              <p>Umur : {{ profile.umur }}</p>
              <p>Domisili : {{ profile.domisili }}</p>
              <p>Berat Badan : {{ profile.berat_badan}}</p>
              <p>Tinggi Badan : {{ profile.tinggi_badan}}</p>
          </fieldset>
          <div class="form-group" >
             
              <button href ="{% url 'akun:profile_dua' %}"class="btn btn-outline-info" type="submit">Submit</button>
          </div>
        </form>
      </div>
    </div>

    <div class="form-group" >     
      <button href ="{% url 'akun:profile_dua' %}"class="btn btn-outline-info" type="submit">cek</button>
    </div>
{% endblock content %}