akun/urls.py
from django.urls import path
from . import views

app_name ='akun'

urlpatterns = [
    path('', views.profile, name ='profile'),
    path('hasilprofile/', views.profile_dua , name = 'profile_dua'),
    path('editprofile/<int:pk>/', views.update_profile , name = 'update_profile'),
    path('cobalist/', views.cobaList, name = 'list'),
    path('cobacreate/', views.cobaCreate, name = 'create'),

]

coronahworry/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('workout/', include(('workout.urls', 'workout'), namespace = 'workout')),
    path('profile/', include(('akun.urls', 'akun'), namespace = 'akun')),
    path('assessment/', include(('assessment.urls', 'assessment'), namespace='assessment')),
    path('curhat/', include(('komentar.urls', 'komentar'), namespace = 'komentar')),
    path('curhat/', include(('postingan.urls', 'postingan'), namespace = 'postingan')),
    path('', include(('main.urls', 'main'), namespace='main')),
]



workout/urls.py
from django.urls import path

from . import views

app_name = 'workout'

urlpatterns = [
    path('cobalist/', views.cobaList, name = 'list'),
    path('cobacreate/', views.cobaCreate, name = 'create'),
    path('list/', views.list_work, name='listwork'),
    path('create/', views.create_work, name='creatework'),
    path('', views.hitung_bmi, name='hitungbmi'),
]

workout/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

from django.db.models.deletion import CASCADE

# Create your models here.
class Work(models.Model):
    title = models.CharField(max_length=100)
    desc = models.TextField()
    duration = models.CharField(max_length=20)
    published = models.DateTimeField(editable=False, default=datetime.now, blank=True)
    user = models.ForeignKey(User, on_delete=CASCADE, default=None)

workout/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _ 
from .models import Work

class WorkForm(forms.ModelForm):
    class Meta:
        model = Work
        fields = ('title', 'desc', 'duration', 'user', )
        widgets = {'user' : forms.HiddenInput()}
    

workout/views.py
from django.shortcuts import render, redirect
from akun.models import Profile
from .models import Work
from .forms import WorkForm
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
 
# Create your views here.

# Fungsi untuk menampilkan hasil BMI dari user tertentu
def hitung_bmi(request):
    if request.user.is_authenticated:
        get_data = Profile.objects.get(user = request.user)
        bmi = get_data.hitung_bmi()
        print(bmi)
        context = {
                "get_data" : get_data,
                "bmi" : bmi
            }
        return render(request, "workout/hasilBMI.html", context)
    else:
        return redirect('main:login')

#Fungsi untuk menampilkan form dan membuat aktivitas baru
def create_work(request):
    if request.user.is_authenticated:
        id = request.user
        form = WorkForm(initial = {'user':id})
        if request.method == "POST":
            form = WorkForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect("workout:listwork")
        context = {'form':form}
        return render(request, 'workout/create.html', context)
    else:
        return redirect('main:login')

# fungsi Json
@csrf_exempt
def cobaCreate(request):
    responJson = {'error':'method not allowed'}
    status_code = 405

    if request.method == 'POST':
        title = request.POST.get('title')
        desc = request.POST.get('desc')
        duration = request.POST.get('duration')

        Work.objects.create(title=title, desc=desc, duration=duration)

        responJson = {'status': 'ok'}
        status_code = 200

        responJson["error"] = "something went wrong"
        status_code = 500

    return JsonResponse(responJson, status=status_code)
        
#Fungsi untuk menampilkan semua aktivitas yang telah dipost
def list_work(request):
    if request.user.is_authenticated:
        get_data = Profile.objects.get(user = request.user)
        bmi = get_data.hitung_bmi()
        print(bmi)
        works = Work.objects.all().order_by('-published')
        context = {'works':works, 'bmi':bmi}
        return render(request, 'workout/list.html', context)
    else:
        return redirect('main:login')

# Fungsi Json
def cobaList(request):
    if not request.user.is_authenticated:
        responJson = {'error': 'forbidden'}
        status_code = 403

    else :
        works = Work.objects.all()
        responContent = []
        for work in works :
            temp = {'user':work.user.username,'title':work.title, 'desc':work.desc, 'duration':work.duration, 'published':work.published}
            responContent.append(temp)
        responJson = {'content':responContent}
        status_code = 200
    return JsonResponse(responJson, status=status_code)

templates/workout/create.html
{% extends '../base/base.html' %}
{% load static %}

{% block title %}
    CreateActivity
{% endblock title %}

{% block customcss %}
<link rel="stylesheet" href="{% static 'css/workout.css' %}">
{% endblock %}

{% block content %}
<div class="wrapper col-12 my-5 py-3">
    <div class="container mt-5">
        <h3 class="text-xs text-center font-weight-bold text-uppercase mb-1">Bagikan kegiatanmu dengan orang lain</h3>
        <div class="rowa">
            <div class="col-xl-12 col-md-12 my-3">
                <div class="card box-shadow h-100">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                               <form method="POST", action="">
                                {% csrf_token %}
                                {{ form.user }}
                                <div class="form-group" id="title">
                                    <label>Judul :</label>
                                    <input name='title' id='ti' class="form-control" cols="40" rows="5" required maxlength="200" placeholder="Tulis judul">
                                </div>
                                <div class="form-group" id="desc">
                                    <label>Deskripsi :</label>
                                    <textarea name="desc" id='de' class="form-control" cols="40" rows="5" required maxlength="200" placeholder="Tulis deskripsi"></textarea>
                                </div>
                                <div class="form-group" id="duration">
                                    <label>Durasi :</label>
                                    <select  name="duration" id='dur' class="form-control" required>
                                        <option value="0-30 menit">0-30 menit</option>
                                        <option value="30 menit - 1 jam">30 menit - 1 jam</option>
                                        <option value="1 - 1.5 jam">1 - 1.5 jam</option>
                                        <option value="1.5 - 2 jam">1.5 - 2 jam</option>
                                    </select>
                                </div>
                                <button class="btn btn-info" id="submit" value="Submit">Kirim</button>
                                </form>
                                <hr>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    
        
    </div>
</div>
<div class="change-theme d-flex align-items-center mb-5 mt-3">
    <input type="checkbox" hidden="hidden" id="theme">
    <label class="switch" for="theme"></label>
</div>

{% endblock %}

{% block customjs %}
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/list.js' %}"></script>
<script src="{% static 'js/workout.js' %}"></script>
{% endblock %}

templates/workout/hasilBMI.html
{% extends '../base/base.html' %}
{% load static %}

{% block title %}
    BMI 
{% endblock title %}

{% block customcss %}
<link rel="stylesheet" href="{% static 'css/workout.css' %}">
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <div class="col-xl-12 col-md-12 my-3" >
            <div class="wrapper">
            <div class="card box-shadow h-100">
                <div class="card-body">   
                    <div class="img">
                        {% if bmi == 0 %}
                        <img src="{% static 'img/workout/empty.svg' %}" width=20% style="margin: auto; display: block;">
                        {% elif bmi < 18.5 %}
                        <img src="{% static 'img/workout/sad.svg' %}" width=20% style="margin: auto; display: block;">
                        {% elif bmi > 18.5 and bmi < 25 %}
                        <img src="{% static 'img/workout/happy.svg' %}" width=20% style="margin: auto; display: block;">
                        {% elif bmi > 25 and bmi < 29.9 %}
                        <img src="{% static 'img/workout/pre.svg' %}" width=20% style="margin: auto; display: block;">
                        {% elif bmi > 29.9 and bmi < 32.9 %}
                        <img src="{% static 'img/workout/sad.svg' %}" width=20% style="margin: auto; display: block;">
                        {% elif bmi > 32.9 %}
                        <img src="{% static 'img/workout/class1.svg' %}" width=20% style="margin: auto; display: block;">
                        {% endif %}
                    </div>
              
    
                {% if bmi != 0 %}
                <div class="text-xs text-center font-weight-bold mt-5">
                <h3><b>Halo {{user.username}}</b></h3>
                <p>Kamu memiliki berat badan sebesar {{get_data.berat_badan}} kg dan tinggi badan {{ get_data.tinggi_badan }} cm,</p>
                <p>maka BMI mu sebesar :</p>
                <h3 class="font-weight-bold my-3">{{bmi}}</h3>
                <div class="my-4 font-weight-bold">
                    {% if bmi < 18.5 %}
                        <p>BMI mu tergolong "Underweight"</p>
                    {% elif bmi > 18.5 and bmi < 25 %}
                        <p>BMI mu tergolong "Normal"</p>
                    {% elif bmi > 25 and bmi < 29.9 %}
                        <p>BMI mu tergolong "Preobese"</p>
                    {% elif bmi > 29.9 and bmi < 34.9 %}
                        <p>BMI mu tergolong "Obese Class I"</p>
                    {% elif bmi > 35 %}
                        <p>BMI mu tergolong "Obese Class II"</p> 
                    {% endif %}
                </div>
                </div>
                {% else %}
                <div class="text-xs text-center font-weight-bold mt-5">
                    <p>Tolong update profile mu terlebih dahulu</p>
                </div>
                {% endif %}
            </div>
        </div>
        </div>
        <div class="change-theme d-flex align-items-center mt-4">
            <input type="checkbox" hidden="hidden" id="theme">
            <label class="switch" for="theme"></label>
        </div>
    </div>
</div>
{% endblock %}

{% block customjs %}
<script src="{% static 'js/bmi.js' %}"></script>
{% endblock %}
   

templates/workout/list.html
{% extends '../base/base.html' %}
{% load static %}

{% block title %}
    Activity
{% endblock title %}

{% block customcss %}
<link rel="stylesheet" href="{% static 'css/workout.css' %}">
{% endblock %}

{% block content %}
<div class="container mt-5">
    {% if bmi == 0 %}
    <div class="col-xl-12 col-md-12 my-3">
        <div class="col-xl-12 col-md-12 my-3">
        <div class="card box-shadow h-100">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs text-center font-weight-bold text-uppercase mb-1">
                            <p>BMI mu masih kosong</p>
                            <p>update profilmu terlebih dahulu</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
     </div>
</div>

    {% else %}
    <div class="col-xl-12 col-md-12 my-3">
    <h3 class="text-xs text-center font-weight-bold text-uppercase mb-1">Bagikan juga kegiatanmu <a href="{% url 'workout:creatework' %}" style="color:#065a6ec7;;">disini</a></h3>
    <div class="col-xl-12 col-md-12 my-3">
    <div class="card box-shadow h-100">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-xs text-center font-weight-bold text-uppercase mb-1">
                            {% if bmi < 18.5 %}
                            <p>BMI mu tergolong "Underweight"</p>
                            <p>Workout yang dapat kamu coba berdasarkan BMI mu</p>
                            <div class="img">
                                <img src="{% static 'img/workout/badminton.svg' %}" width=30%>
                            </div>
                        {% elif bmi > 18.5 and bmi < 25 %}
                            <p>BMI mu tergolong "Normal"</p>
                            <p>Workout yang dapat kamu coba berdasarkan BMI mu</p>
                            <div class="img">
                                <img src="{% static 'img/workout/swim.svg' %}" width=30%>
                            </div>
                        
                        {% elif bmi > 25 and bmi < 29.9 %}
                            <p>BMI mu tergolong "Preobese"</p>
                            <p>Workout yang dapat kamu coba berdasarkan BMI mu</p>
                            <div class="img">
                                <img src="{% static 'img/workout/basket.svg' %}" width=30%>
                            </div>
                            
                        {% elif bmi > 29.9 and bmi < 34.9 %}
                            <p>BMI mu tergolong "Obese Class I"</p>    
                            <p>Workout yang dapat kamu coba berdasarkan BMI mu</p>
                            <div class="img">
                                <img src="{% static 'img/workout/drill.svg' %}" width=30%>
                            </div>
                     
                        {% elif bmi > 35 %}
                            <p>BMI mu tergolong "Obese Class II"</p>
                            <p>Workout yang dapat kamu coba berdasarkan BMI mu</p>
                            <div class="img">
                                <img src="{% static 'img/workout/weightlift.svg' %}" width=30%>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="change-theme d-flex align-items-center mb-5 mt-3">
    <input type="checkbox" hidden="hidden" id="theme">
    <label class="switch" for="theme"></label>
</div>
<!------------------------------------->
    <div class="col-xl-12 col-md-12 my-3" >
        <div class="row my-3" id="ini-hasil">
                  <!--hasilnya disini--> 
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

{% block customjs %}
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/list.js' %}"></script>
<script src="{% static 'js/workout.js' %}"></script>
{% endblock %}

